#!/usr/bin/env python

import random

if __name__ == '__main__':
    r = random.random
    try:
        while True:
            print r()
    except KeyboardInterrupt:
        # the user quit
        pass
    except IOError:
        # happens on a broken pipe
        pass
