#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  range.py
#  shelly
#

"""
Calculate a running range and display to stdout.
"""

import sys
import optparse


from consoleLog.slot import Slot


def running_range(istream=sys.stdin):
    print '%18s %18s %18s' % ('min', 'max', 'delta')
    s = Slot()
    _min = float('inf')
    _max = float('-inf')
    try:
        for line in sys.stdin:
            v = float(line)
            dirty = False
            if v < _min:
                _min = v
                dirty = True
            if v > _max:
                _max = v
                dirty = True

            if dirty:
                s.update('%18s %18s %18s' % (_min, _max, _max - _min))
    except KeyboardInterrupt:
        pass
    except IOError:
        pass
    s.update('%18s %18s %18s' % (_min, _max, _max - _min))

    print


def _create_option_parser():
    usage = \
"""%prog [options]

Displays a running maximum of values from stdin."""

    parser = optparse.OptionParser(usage)

    return parser


def main(argv):
    parser = _create_option_parser()
    (options, args) = parser.parse_args(argv)

    if args:
        parser.print_help()
        sys.exit(1)

    running_range(*args)


if __name__ == '__main__':
    main(sys.argv[1:])
