#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  symbolic.py
#  bin
#
#  Created by Lars Yencken on 2012-01-11.
#  Copyright 2012 Lars Yencken. All rights reserved.
#

"""
Symbolic algebra for Python.
"""

import os
import sys
import optparse

from sympy import *

def symbolic(expression):
    pass

#----------------------------------------------------------------------------#

def _create_option_parser():
    usage = \
"""%prog [options] arguments

Insert usage message."""

    parser = optparse.OptionParser(usage)

    return parser

def main(argv):
    parser = _create_option_parser()
    (options, args) = parser.parse_args(argv)

    if args:
        parser.print_help()
        sys.exit(1)

    my_function(*args)

#----------------------------------------------------------------------------#

if __name__ == '__main__':
    main(sys.argv[1:])
